#!/bin/bash
unset HOSTFILE;
unset MAC;
unset MACS;
unset HOST;
unset HOSTS;
unset IFC;
source /var/lib/pmon/general;
source /etc/pmon/pmon.conf
DATE="$(date)";
MACS=();
HOSTS="/tmp/pmon/hosts.tmp"
declare -A HOSTDATA;
c=1;
while read -r line; do
	if [[ ! $line ]] || [[ $line =~ '#' ]]; then
		continue;
	fi
	if [[ $line  =~ 'M-' ]]; then
		MAC=${line:2};
		isMac "$MAC" || { invalidmacMsg "$MAC" && exit 2; }
		HOSTDATA[mac]="$MAC";
		{ HOST=$(macHaveIp "$MAC") && HOSTDATA[IP]="$HOST" && pingHost $HOST; } || ipNotFoundMsg $MAC && ipNotFoundMsg $MAC >> $ERRLOG;
		continue;
	fi
	dest=$line;
	HOSTDATA[host]="host";  
	if isIp $dest; then
		HOSTDATA[IP]=$dest;
	else
		HOSTDATA[IP]=""
	fi
	pingHost $dest;

	echo "HOST$c { 
	HOST:\"${HOSTDATA[host]}\",
	IP:${HOSTDATA[IP]},
	PINGPID:${HOSTDATA[PINGPID]}
}" >> $HOSTS;
	let c=c+1
done < $HOSTSFILE;
#listen
while true; do
	continue;
done;

