#!/bin/bash
source pmon-functions;
unset HOSTFILE;
unset MAC;
unset MACS;
unset HOST;
unset HOSTS;
unset IFC;

HOSTFILE='hosts.list';
MACS=();
while read -r line; do
	if [[ ! $line ]] || [[ $line =~ '#' ]]; then
		continue;
	fi
	if [[ $line  =~ 'M-' ]]; then
		MAC=${line:2};
		pingHost 'mac' $MAC;
		continue;
	fi
	HOST=$line;
	pingHost 'host' $HOST;
done < $HOSTFILE;


